### ISSUE TITLE
example clinical data table

### ISSUE THREAD

**Issue by Aminkhormali** [KatherLab/marugoto#11]
Is there a possibility that you can include a sample clinical table (tcga-crc-dx/TCGA-CRC-DX_CLINI.xlsx) in the repository? This would be a huge help in understanding the whole implementation.

**Comment by sandrocarollo** [comment]
I agree completely. I would like to use this as well, but without a sample file structure for the input data, this is not possible.

**Comment by ALjone** [comment]
During testing and by inspecting the code, it seems like the only thing that is required is that "clini_table" contains a "PATIENT" column. Any other columns that exist in the clinical table will just be appended to the train.csv/valid.csv generated by running it, and is not strictly necessary. The PATIENT column must of course overlap with the "slide_table", since only patients that show up in both are considered.

**Comment by Avic3nna** [comment]
@Aminkhormali @ALjone 

You can find our latest protocol + accompanying documentation and manual in the following link: https://github.com/KatherLab/STAMP

The paper will answer most of the questions you might have. New issues can be opened there, if you'd like. Thank you!
